/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package byui.cit260.chooseYourOwnAdventure.frames;

import byui.cit260.chooseYourOwnAdventure.control.GameControl;
import byui.cit260.chooseYourOwnAdventure.control.RescueControl;
import byui.cit260.chooseYourOwnAdventure.control.ResourceControl;
import byui.cit260.chooseYourOwnAdventure.model.Resource;
import chooseyourownadventure.ChooseYourOwnAdventure;

/**
 *
 * @author kristyknapp
 */
public class HelpMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form HelpMenuFrame
     */
    public HelpMenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JBGameGoals = new javax.swing.JButton();
        JBScenarios = new javax.swing.JButton();
        JBResourcesHelp = new javax.swing.JButton();
        JBQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextPaneHelp = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Eurostile", 1, 36)); // NOI18N
        jLabel1.setText("Help Menu");

        JBGameGoals.setText("Goals");
        JBGameGoals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGameGoalsActionPerformed(evt);
            }
        });

        JBScenarios.setText("Scenarios");
        JBScenarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBScenariosActionPerformed(evt);
            }
        });

        JBResourcesHelp.setText("Resources");
        JBResourcesHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBResourcesHelpActionPerformed(evt);
            }
        });

        JBQuit.setText("Exit");
        JBQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBQuitActionPerformed(evt);
            }
        });

        JTextPaneHelp.setFont(new java.awt.Font("Meiryo", 0, 14)); // NOI18N
        JTextPaneHelp.setText("Need Help? Click on the different buttons to learn more about the game, Choose Your Own Adventure. \nGood Luck!");
        jScrollPane1.setViewportView(JTextPaneHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBResourcesHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBScenarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBGameGoals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBGameGoals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBScenarios)
                        .addGap(18, 18, 18)
                        .addComponent(JBResourcesHelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBQuit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBGameGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGameGoalsActionPerformed
        this.JTextPaneHelp.setText("The goal of the game, simply is to get off the island"
                + "by any means possible. You choose an area of the island to explore,"
                + "find resources to escape, all the while keeping yourself healthy enough"
                + "to survive. Every action you make costs you, so you must constantly keep"
                + "healthy and any survivors you might find and take care of. If you move,"
                + "you lose health, if you attempt to escape, you lose health, if you"
                + "hardly breath you lose health, so weigh your options carefully."
                +"The outcome of your rescue is entirely randomly generated."
                + "You might be successful on your first try, or you might not be until"
                + "your 12th try. Always keep in mind that those attempts cost your health as well.");
    }//GEN-LAST:event_JBGameGoalsActionPerformed

    private void JBScenariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBScenariosActionPerformed
        this.JTextPaneHelp.setText("There are many different senarios that you will come across"
        + "within the game. First being choosing your section of the"
        + "island you will interact with, the beach, or the cliffs."
        + "The beach offers better rescue options while the cliffs"
        + "offers better resources for survival. It's your choice."
        +"The next choices you will come across are up to your previous choices."
        + "You must start to explore the part of the island you are on and "
        + "collect resources. Logs, rocks and vines are your means of rescue,"
        + "while food and water are impartiveto your long term survival."
        + "Moving locations and attempting rescue will cost your health."
        + "You must balance working with your eating, drinking and sleeping.");
    }//GEN-LAST:event_JBScenariosActionPerformed

    private void JBResourcesHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBResourcesHelpActionPerformed
        //Get the sorted resources
            Resource[] resources = GameControl.getSortedResources();
        //Display them
            
         

             this.JTextPaneHelp.setText("List of Resources"
                + GameControl.sortedResources(resources));
                
             //Attempt Below
             /*"\n\n\tDescription"
                + collectResources.getDescription()
                +"\n\tRequired Amount"
                + collectResources.getRequiredAmount()
                +"\n\tIn Stock"
                + collectResources.getQuantityInStock()
             */  
    }//GEN-LAST:event_JBResourcesHelpActionPerformed

    private void JBQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBQuitActionPerformed
        //Quit or Exit
        ChooseYourOwnAdventure.getMainMenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGameGoals;
    private javax.swing.JButton JBQuit;
    private javax.swing.JButton JBResourcesHelp;
    private javax.swing.JButton JBScenarios;
    private javax.swing.JTextPane JTextPaneHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
